"""initial schema

Revision ID: 92e24cd776c3
Revises: 
Create Date: 2025-11-19 19:56:12.852097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92e24cd776c3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', sa.Text(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('metadata', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_chunks_document_index')
    )
    op.create_table('chunk_embeddings',
    sa.Column('chunk_id', sa.Integer(), nullable=False),
    sa.Column('vector', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chunk_id')
    )
    op.create_table('entities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chunk_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('metadata', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entity_embeddings',
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('vector', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_table('relations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('predicate', sa.String(length=128), nullable=False),
    sa.Column('subject_entity_id', sa.Integer(), nullable=True),
    sa.Column('subject_name', sa.String(length=255), nullable=True),
    sa.Column('object_entity_id', sa.Integer(), nullable=True),
    sa.Column('object_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['object_entity_id'], ['entities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_entity_id'], ['entities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relations')
    op.drop_table('entity_embeddings')
    op.drop_table('entities')
    op.drop_table('chunk_embeddings')
    op.drop_table('chunks')
    op.drop_table('documents')
    # ### end Alembic commands ###
